### ISSUE TITLE
RSpec uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG

### ISSUE THREAD

**Issue by christianrolle** [palkan/action-cable-testing#12]
Following the advised RSpec approach, running the RSpec test fails with:

```
/home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers/erb.rb:90:in `<class:ERB>': uninitialized constant ActionView::Template::Handlers::ERB::ENCODING_FLAG (NameError)
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers/erb.rb:76:in `<module:Handlers>'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers/erb.rb:5:in `<class:Template>'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers/erb.rb:4:in `<module:ActionView>'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers/erb.rb:3:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/handlers.rb:12:in `extended'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template.rb:112:in `extend'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template.rb:112:in `<class:Template>'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template.rb:8:in `<module:ActionView>'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template.rb:6:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/template/resolver.rb:4:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/actionview-5.0.6/lib/action_view/testing/resolvers.rb:1:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/rspec-rails-3.7.1/lib/rspec/rails/view_rendering.rb:1:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/rspec-rails-3.7.1/lib/rspec/rails.rb:9:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/action-cable-testing-0.1.2/lib/action_cable/testing/rspec.rb:4:in `<top (required)>'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/christian/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/christian/work/evopark/backend/spec/rails_helper.rb:17:in `<top (required)>'
```

After inserting that **before** requiring the `action_cable/testing/rspec`:

```
# spec/rails_helper.rb
require File.expand_path("../../config/environment", __FILE__)
require "action_cable/testing/rspec"
```

it went better, but still failed with:

```**************************************************
⛔ WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.
**************************************************
/home/christian/work/evopark/backend/spec/rails_helper.rb:99:in `block in <top (required)>': uninitialized constant EmailSpec (NameError)
	from /home/christian/.rvm/gems/ruby-2.3.4@evopark/gems/rspec-core-3.7.0/lib/rspec/core.rb:98:in `configure'
	from /home/christian/work/evopark/backend/spec/rails_helper.rb:49:in `<top (required)>'
```

the line `99` there looks like:

```
# spec/rails_helper.rb
# line 49
RSpec.configure do |config|
  # ...
  #  line 99
  config.include EmailSpec::Helpers, type: :mailer
  # ...
end
```

Any hint is appreciated.

**Comment by palkan** [comment]
First, you should require `action_cable/testing/rspec` after `environment.rb` (that's exactly what Readme states).

I guess, you should add `require 'email_spec/rspec'` too (after loading env) (see https://github.com/email-spec/email-spec#rspec-31).

**Comment by christianrolle** [comment]
@palkan Thank you very much! Requiering `'email_spec/rspec'` helped.
