### ISSUE TITLE
Error in rspec test, subscribe action ...

### ISSUE THREAD

**Issue by yamanaltereh** [palkan/action-cable-testing#2]
I'm trying to test successful subscribe with channel ...
and I'm getting this error .. because of calling `stream_from` ...

```
     NoMethodError:
       undefined method `server' for #<ActionCable::Channel::ConnectionStub:0x007f84a96be678>
     # /Users/yaman/.rvm/gems/ruby-2.3.1/gems/actioncable-5.0.0.1/lib/action_cable/channel/streams.rb:85:in `stream_from'
.....
```

`server` method is missing from `ConnectionStub`, I just tried to add it like this:
```ruby
class ConnectionStub
  attr_reader :transmissions, :identifiers, :subscriptions, :logger

  def initialize(identifiers = {})
    ...
  end

  def server
    ActionCable.server
  end

  ...
end
```

and it works! .. any idea ?! 

my original code is like this:

```ruby
class ConversationChannel < ApplicationCable::Channel
  def subscribe_to_channel
    stop_all_streams
    stream_from conversation_id
  end
end
```

**Comment by palkan** [comment]
Hi @yamanaltereh,

How does your test look like?

**Comment by palkan** [comment]
@yamanaltereh 

One more question: why do you override `subscribe_to_channel` in your channel class instead of defining `subscribed` callback? I guess, that's the problem; `#subscribe_to_channel` is an internal method, you should not patch it.

**Comment by yamanaltereh** [comment]
@palkan Ah, I see .. actually the problem was .. when I use `subscribed` I get this error:
```
NoMethodError:
       private method `subscribe_to_channel' called for #<ConversationChannel:0x007fc1940c7418>
       Did you mean?  unsubscribe_from_channel
     # /Users/yaman/.rvm/gems/ruby-2.3.1/gems/action-cable-testing-0.1.0/lib/action_cable/channel/test_case.rb:201:in `subscribe'
```

after looking at the source code .. I thought it should be `subscribe_to_channel` ...

**Comment by yamanaltereh** [comment]
@palkan my rspec test is like this:
```ruby
RSpec.describe ConversationChannel, type: :channel do
...
end
```

**Comment by palkan** [comment]
@yamanaltereh It turned out that the problem was with Rails 5.0.0.1 calling `subscribe_to_channel` during the channel's initialization (fixed by myself, btw, in 5.0.1).

Fixed by #3 and released as 0.1.1.

**Comment by yamanaltereh** [comment]
@palkan okay thanks, updated gem to release `0.1.1` .. and it's working now 👍

**Comment by mateuszdw** [comment]
Hello,
I see the same error on rails v5.1.0 & action-cable-testing v0.1.2
`
undefined method 'server' for #<ActionCable::Channel::ConnectionStub:0x00007fb5a758b998>
`
when use periodically timer
 
```ruby
class TestChannel < ApplicationCable::Channel
  periodically every: 5.seconds do

  end

  def subscribed
    stream_from "some_channel"
  end
end
```
spec
```ruby
require 'rails_helper'

RSpec.describe TestChannel, type: :channel do

  it "subscribe" do
    subscribe
    expect(subscription).to be_confirmed
  end

end

```
Any idea how to get around this problem?
Thanks

**Comment by palkan** [comment]
Hi, @mateuszdw!

Could you, please, provide the error backtrace?

**Comment by mateuszdw** [comment]
Hi @palkan, sorry for delay. Here it is
```ruby
     NoMethodError:
       undefined method `server' for #<ActionCable::Channel::ConnectionStub:0x00007fcd1f40ff08>
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/channel/periodic_timers.rb:66:in `start_periodic_timer'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/channel/periodic_timers.rb:61:in `block in start_periodic_timers'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/channel/periodic_timers.rb:60:in `each'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/channel/periodic_timers.rb:60:in `start_periodic_timers'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/engine.rb:66:in `block (3 levels) in <class:Engine>'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/actioncable-5.1.0/lib/action_cable/channel/base.rb:176:in `subscribe_to_channel'
     # /Users/matt/.rvm/gems/ruby-2.4.2@chatp-rails5/gems/action-cable-testing-0.1.2/lib/action_cable/channel/test_case.rb:200:in `subscribe'
     # ./spec/channels/test_channel_spec.rb:6:in `block (2 levels) in <top (required)>'
```
