### ISSUE TITLE
Strange behaviour of expect(subscription).to be_rejected

### ISSUE THREAD

**Issue by prem-prakash** [palkan/action-cable-testing#50]
```ruby
# app/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      if (verified_user = env['warden'].user)
        verified_user
      else
        reject_unauthorized_connection
      end
    end
  end
end
```

```ruby
# app/channels/conversation_channel.rb
class ConversationChannel < ApplicationCable::Channel
  def subscribed
    lead = Lead.find_by(id: params['lead_id'], user_id: identifier.id)
    reject if lead.blank?
    stream_from "conversation_#{params['lead_id']}_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end

  def receive(data)
    lead = Lead.find_by!(id: params['lead_id'], user_id: current_user.id)
    Messenger::SendConversationMessage.send_message(text: data['text'], lead: lead)
  end
end
```

```ruby
# spec/channels/conversation_channel_spec.rb
require 'rails_helper'

RSpec.describe ConversationChannel, type: :channel do
  let(:lead) { create(:lead) }
  let(:user) { lead.user }

  before do
    stub_connection lead_id: lead.id, identifier: user
  end

  it 'rejects when no lead id' do
    subscribe
    expect(subscription).to be_rejected
    expect(subscription).not_to have_streams
  end

  it 'subscribes to a stream when lead id is provided' do
    subscribe(lead_id: lead.id)
    expect(subscription).to be_confirmed
    expect(subscription).to have_stream_from("conversation_#{lead.id}_channel")
  end
end
```

RSPEC output

```sh
rspec ./spec/channels/conversation_channel_spec.rb

ConversationChannel
  rejects when no lead id (FAILED - 1)
  subscribes to a stream when lead id is provided

Failures:

  1) ConversationChannel rejects when no lead id
     Failure/Error: expect(subscription).not_to have_streams

     RuntimeError:
       Must be subscribed!
     # /Users/prakash/.rvm/gems/ruby-2.6.1/gems/action-cable-testing-0.5.0/lib/action_cable/testing/channel/test_case.rb:289:in `check_subscribed!'
     # ./spec/channels/conversation_channel_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:58:in `block (2 levels) in <top (required)>'

Finished in 0.59609 seconds (files took 2.91 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/channels/conversation_channel_spec.rb:11 # ConversationChannel rejects when no lead id
```

**Comment by palkan** [comment]
This is caused by the second line in your example:

```ruby
it 'rejects when no lead id' do
    subscribe
    # this should pass
    expect(subscription).to be_rejected
    # this fails, 'cause we check that subscription exists and is confirmed
    expect(subscription).not_to have_streams
end
```

In general, you don't need to check that the rejected subscription has no streams, 'cause it couldn't have any streams by design (when subscription is rejected `stop_all_streams` is called).

**Comment by prem-prakash** [comment]
I got it, thank you

**Comment by yannickschuchmann** [comment]
thx @palkan, makes sense.
I also got into this pitfall but using the [rspec example for a channel](https://github.com/palkan/action-cable-testing#rspec-usage).

I guess it's worth to slightly adjust that part of the README. :)

**Comment by palkan** [comment]
@yannickschuchmann Thanks for the suggestion! Updated the readme.

> I can't imagine any good example for using not_to have_streams for channels then at all?

It is useful if you have smth like:

```ruby
stream_from "whatever" if some_condition
```

And it's based on the real example (which we cannot publish here 🙂).

**Comment by yannickschuchmann** [comment]
ahh okay, @palkan. Thanks for pointing that out :)
